# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mov-9',
                'doc_host': 'https://daveramseymusic.github.io',
                'git_url': 'https://github.com/daveramseymusic/mov-9',
                'lib_path': 'mov_9'},
  'syms': {'mov_9.core': {'mov_9.core.foo': ('core.html#foo', 'mov_9/core.py')}}}